### ISSUE TITLE
[ios] RadListView header footer cannot be set to transparent NS 5.1.1 / Angular 7

### ISSUE THREAD

**Issue by zurie** [NativeScript/nativescript-ui-feedback#1010]
Is it possible to tell me what view needs to be overridden to set header and footer to transparent in a RadListView header and footer template?  I am able to set cells / pull to refresh / and other views to transparent but I am unable to find out what UIView is behind the header footer?  When setting the topmost view of the header /footer to transparent I am left with another view underneath.   is there someone internally who can give more insignt on what I can target to override? Do i need to create a new delegate and override the header footer component? or can it be done in the angular component or (loaded) or onOnit / etc.

**Comment by tsonevn** [comment]
Hi @zurie,
Currently, there is no option available, that allows accessing the native view of the RadListView's header element. I will mark this as a feature and we will research how to enable similar functionality for the ListView component.

**Comment by tgpetrov** [comment]
Hi @zurie 
Since nativescript-ui-listview@6.3.0 we have removed the white layer on some views of RadListView on iOS including the header and the footer. You should now be able to make them transparent without any native code, simply setting a proper header/footer templates should suffice.
