### ISSUE TITLE
Demo for autocomplete crash when suggest view doesn't close on navigate back

### ISSUE THREAD

**Issue by elena-p** [NativeScript/nativescript-ui-feedback#1037]
When type in the autocomplete to show suggest view, then suspend the demo app and resume it, navigating back to home page doesn't close the suggest view. When select an item from the view, the app crashes.

### Which platform(s) does your issue occur on?
Android

### Please tell us how to recreate the issue in as much detail as possible.

1. Open the demo app on Android device
2. Navigate to getting started example
3. Type "A" in the autocomplete to open the suggest view
4. Suspend the app, then resume it
5. Navigate back with the device's back button
6. Tap on an item from the suggest view.

Here is a [video](https://www.screencast.com/t/VO7qjbgJY8) describing the issue.

Actual: The app crashes
Expected: The suggest view should be closed.

**Comment by WebDaMa** [comment]
Also have this issue:

tap the autocomplete field go to a different page and app crashes.

`System.err: com.tns.NativeScriptException: 
System.err: Calling js method setPrimaryItem failed
System.err: 
System.err: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Enum.name()' on a null object reference
System.err:     com.telerik.widget.autocomplete.RadAutoCompleteTextView.initSavedState(RadAutoCompleteTextView.java:1710)
System.err:     com.telerik.widget.autocomplete.RadAutoCompleteTextView.onSaveInstanceState(RadAutoCompleteTextView.java:1684)
`
`  "nativescript": {
    "id": "org.nativescript.XApp",
    "tns-android": {
      "version": "5.3.1"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "nativescript-angular": "^7.2.3",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-dataform": "^3.9.0",
    "nativescript-ui-sidedrawer": "^5.0.0",
    "reflect-metadata": "~0.1.10",
    "rxjs": "^6.3.3",
    "tns-core-modules": "^5.3.1",
    "zone.js": "^0.8.4"
  },`

**Comment by DimitarTodorov** [comment]
Fixed with https://github.com/NativeScript/nativescript-ui-autocomplete/releases/tag/v4.1.0
