### ISSUE TITLE
RadCalendar 4.0.0 broken selection and alignment

### ISSUE THREAD

**Issue by edusperoni** [NativeScript/nativescript-ui-feedback#1065]
### Tell us about the problem
When updating `nativescript-ui-calendar` to 4.0.0, Month selection style Shape and Color are ignored.

`CalendarCellAlignment` has no "Center", only `VerticalCenter` (center+right) and `HorizontalCenter` (top+center).

### Which platform(s) does your issue occur on?
Android. haven't tested on iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** 4.0.0
- **CLI:** 5.2.4
- **Cross-platform modules:** 5.2.2 (also with 5.3.0)
- **Runtime(s):** 5.2.0 and 5.3.0

### Please tell us how to recreate the issue in as much detail as possible.
Run the demo application and try selecting the days. It won't respect the `selectionShape` and `selectionShapeColor`, also, there's no way to center the content (without a hack). The same parameters work with the previous version.

1. Open `app/home/env.ts`.
2. Set `NEWCALENDAR` to `true` to use 4.0.0 and `false` to use the previous version.
3. Check `app/home/calendarStyle.ts` and `oldCalendarStyle.ts`.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

https://play.nativescript.org/?template=play-ng&id=8KZTsD

**Comment by zbranzov** [comment]
Released in nativescript-ui-calendar@4.1.0
