### ISSUE TITLE
DateTimeContinuousAxis step interval

### ISSUE THREAD

**Issue by xpete** [NativeScript/nativescript-ui-feedback#1070]
In a DateTimeContinuousAxis there's a option majorStep that let me show a label value in the axis every hour... How can I show a value every 2 hours or in any other custom step interval?

**Comment by tsonevn** [comment]
Hi @xpete,
If I understand your case correctly, you want to set the `majorStep` for the  `DateTimeContinuousAxis` to 2 hours. Currently, this is not supported and I will log this one as a feature request. You can keep track on it for further info. 
Let me know if I am missing something or your case is different.

**Comment by DimitarTodorov** [comment]
Feature is available in 6.0.0 of nativescript-ui-chart
