### ISSUE TITLE
Issues when using `headerItemTemplate` and `footerItemTemplate` with `groupTemplate` with

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-ui-feedback#1072]
### Tell us about the problem
When using `headerItemTemplate` adding `groupTemplate` and `groupingFunction` causes the `headerItemTemplate` to be overridden by the `groupTemplate` on iOS.

When using `footerItemTemplate` adding `groupTemplate` and `groupingFunction` causes the `footerItemTemplate` to be shown on each "group" on iOS rather than at the end of the list.

### Which platform(s) does your issue occur on?
iOS

**Comment by tgpetrov** [comment]
Fixed in [nativescript-ui-listview@6.2.0](https://github.com/NativeScript/nativescript-ui-feedback/blob/master/releases/listview.md#620-2019-april-19).

**Comment by codytooker** [comment]
Seems like this is happening again.  Specifically with Nativescript Vue
