### ISSUE TITLE
RadSideDrawer displays margin equal to the ActionBar's height when drawerLocation is set to Bottom in xml

### ISSUE THREAD

**Issue by tbozhikov** [NativeScript/nativescript-ui-feedback#1094]
When RadSideDrawer's drawerLocation property is set to Bottom in the XML, the drawer content is set off from the top by the height of the ActionBar

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- "nativescript-ui-sidedrawer": 6.0.0
- **CLI:** 5.3.1
- **Cross-platform modules: 5.3.0
- **Runtime(s):** 5.3.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Open the side drawer demo app (TS)
2. Change [this line](https://github.com/telerik/nativescript-ui-samples/blob/c71f2eee79e12a08dac8e69f3bf8b6092a0760f5/sidedrawer/app/examples/position/drawer-position-page.xml#L4) to:
```xml
<nsDrawer:RadSideDrawer id="sideDrawer" drawerLocation="Bottom" drawerContentSize="280">
```
3. Run the app, go to Position example and open Bottom side drawer
4. The output looks like (note the top margin of the drawer content):
![image](https://user-images.githubusercontent.com/5127806/56655246-e1c08c80-669a-11e9-8f6d-6b0adc6321de.png)

The workaround is to set Bottom location from the code (as it is done in the demo originally)

**Comment by tgpetrov** [comment]
Released with [nativescript-ui-sidedrawer@7.0.0](https://github.com/NativeScript/nativescript-ui-feedback/blob/master/releases/sidedrawer.md#700-2019-july-17)
