### ISSUE TITLE
[RadDataForm] crash in iOS when using groups

### ISSUE THREAD

**Issue by DevPlus31** [NativeScript/nativescript-ui-feedback#1095]
The RadDataForm crash when using groups in iOS (only) 
### Tell us about the problem
When using groups the app crash. after more investigating the code it's stopping at line 961 in
dataform-ui.ios.js  (see screenshot)
![bug](https://user-images.githubusercontent.com/16153522/56958221-99451b00-6b41-11e9-971e-9638c9ab410c.png)

### Which platform(s) does your issue occur on?
_iOS/Android/Both (iOS only) 

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** 4.0.0
- **CLI:** (run `tns --version` to fetch it) 5.3.2
- **Cross-platform modules:** 5.3.0
- **Runtime(s):** 5.3.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application with DataForm and Groups 
2. BOOM. 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://play.nativescript.org/?template=play-vue&id=90I7T2&v=1 

### Solution ### 
Current Code
`let group = <PropertyGroup>this.groups[i];
                let propertyNames: NSMutableArray<any> = NSMutableArray.alloc().initWithCapacity(group.properties.length); // this line crash
                if (group.properties) {
                    for (let j = 0; j < group.properties.length; ++j) {
                        let entityProperty: EntityProperty = <EntityProperty>group.properties[j];
                        propertyNames.addObject(entityProperty.name);
                    }
                }`
Solution 
`let group = <PropertyGroup>this.groups[i];
                if (group.properties) {
                let propertyNames: NSMutableArray<any> = NSMutableArray.alloc().initWithCapacity(group.properties.length); // move to here
                    for (let j = 0; j < group.properties.length; ++j) {
                        let entityProperty: EntityProperty = <EntityProperty>group.properties[j];
                        propertyNames.addObject(entityProperty.name);
                    }
                }`
using groups.properties should be after testing if properties is defined. 

Thanks.

**Comment by zbranzov** [comment]
Released in nativescript-ui-dataform@4.0.1
