### ISSUE TITLE
Android RadListView filter while swiping animation crash

### ISSUE THREAD

**Issue by MartoYankov** [NativeScript/nativescript-ui-feedback#1105]
### Tell us about the problem
With swipe actions enabled and while the swipe animation isn't completed you apply a filtering function the app crashes with an uncaught exception.

```
com.tns.NativeScriptException: 
Calling js method onSwipeProgressChanged failed

Error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
java.util.ArrayList.get(ArrayList.java:437)
com.telerik.widget.list.ListViewDataSourceAdapter.getItemId(ListViewDataSourceAdapter.java:403)
...
```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** 6.1.0
- **CLI:** playground
- **Cross-platform modules:** 5.3.1
- **Runtime(s):** playground

### Please tell us how to recreate the issue in as much detail as possible.
Sample: https://play.nativescript.org/?template=play-tsc&id=uQmH4X&v=1

1. Swipe an item to the right.
2. Quickly tap the heart icon in the ActionBar to trigger filtering before the animation is complete.

**Comment by zbranzov** [comment]
Fixed in nativescript-ui-listview@6.3.1
