### ISSUE TITLE
Datepicker doesn't show selected year

### ISSUE THREAD

**Issue by sotisoti** [NativeScript/nativescript-ui-feedback#1112]
I am using nativescript-ui-dataform 4.0.0, the default value is empty, and for some reason if I select May 14, 2017 from the datepicker, the preview field doesn't show the year.

![Screenshot 2019-05-14 at 7 41 51 PM](https://user-images.githubusercontent.com/9424330/57695359-a48b6100-7680-11e9-844a-dd300bfa6277.png)

![Screenshot 2019-05-14 at 7 46 01 PM](https://user-images.githubusercontent.com/9424330/57695523-119ef680-7681-11e9-9d98-a89781807f1a.png)

**Comment by tsonevn** [comment]
Hi @sotisoti,
Can you share with us your project?

**Comment by sotisoti** [comment]
Hi @tsonevn, here's the repo url:

https://github.com/sotisoti/datepicker, so the selected year is not shown.

**Comment by tsonevn** [comment]
Hi @sotisoti,
Thank you for the provided sample project.
This issue seems to be duplicated to https://github.com/NativeScript/nativescript-ui-feedback/issues/348. You can check the provided temporary solution in issue #348
