### ISSUE TITLE
RadListView combined Swipe & Click (Press)

### ISSUE THREAD

**Issue by kefahB** [NativeScript/nativescript-ui-feedback#1115]
I work with RadListView.

There is way to combien Click and Swipe actions ? if I set swipeActions="true" and selectionBehavior="Press" the Press event will be fired first .. The problem is I use the Press event to navigate and the navigation start on swiping !

I think there is way to achieve this on checking if swipe being to start, then disable Press event .. and when itemSwipeProgressEnded event is fired re bind Press event !!

But I hop there is way more cool to achieve to same result ?

```xml
<lv:RadListView 
            id="listView" 
            items="{{ dataItems }}" 
            row="1" 
            selectionBehavior="Press" 
            itemSelecting="{{ itemSelected }}"
            itemSwipeProgressEnded="onSwipeCellFinished"
            itemSwipeProgressStarted="onSwipeCellStarted" 
            itemSwipeProgressChanged="onCellSwiping" 
            multipleSelection="false"
            swipeActions="true">
```
I try to set a boolean when `itemSwipeProgressStarted` and `itemSwipeProgressEnded` but the problem is the data come from RadListView is not really exact ! and itemSwipeProgressStarted is fired when swipe start from 0 to and itemSwipeProgressEnded x or `-x' same think on opposite direction .. by consequence I can not use this value.

Other think is to use this function : 
```ts
private isSwipeOpend(args: SwipeActionsEventData): boolean {
        const leftDimensions = View.measureChild(
                <View>leftItem.parent,
                leftItem,
                layout.makeMeasureSpec(Math.abs(args.data.x), layout.EXACTLY),
                layout.makeMeasureSpec(mainView.getMeasuredHeight(), layout.EXACTLY));
        console.log(leftDimensions)
        return leftDimensions.measuredWidth !== 0;
    }
```

But if I execute this function on `itemSelecting` event, will return the last `leftDimensions.measuredWidth` registered and not the actual status !

At this stage I try to fin other way !

Thanks

**Comment by tsonevn** [comment]
Hi @kefahB,
In your case, you can try using `itemTapEvent` instead of `itemSelecting `.  The itemTap should not be fired while a swipe action is executed. 
<lv:RadListView 
            id="listView" 
            items="{{ dataItems }}" 
            row="1" 
            selectionBehavior="None" 
            itemSwipeProgressEnded="onSwipeCellFinished"
            itemSwipeProgressStarted="onSwipeCellStarted" 
            itemSwipeProgressChanged="onCellSwiping" 
            itemTap="onItemTap"
            swipeActions="true">
.....
</lv:RadListView>

**Comment by kefahB** [comment]
Hi,
It work big Thanks
