### ISSUE TITLE
RadAutoCompleteTextView CSS Styling

### ISSUE THREAD

**Issue by keithgulbro** [NativeScript/nativescript-ui-feedback#1117]
### Tell us about the problem
When initializing the RadAutoCompleteTextView component, the functionality is excellent! However, when attempting to style various aspects of the component including:

TextField: border-color, background-color, font-size, text-color (color), padding, margin, etc. . 
SuggestionView: background-color, border-color, margin, padding, etc. . .

I can't seem to find documentation regarding the addition of CSS selectors or targeting a given component by it's native name via CSS declarations.

Ideally, it would make sense to be able to do something like the following:

```
RadAutoCompleteTextView {
   background-color: green;
   color: white;
   border-color: yellow;
   border-width: 2;
   border-radius: 5;   
}

RadAutoCompleteTextView .clear-entry-btn {
  background-color: pink;
  color: white;
}

SuggestionView {
   background-color: orange;
   color: black;
}
```

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:

```
{
  "name": "nativescript-vue-project",
  "version": "1.0.0",
  "description": "A native application built with NativeScript-Vue",
  "author": "Keith Gulbro <keithgulbro@example.com>",
  "license": "MIT",
  "nativescript": {
    "id": {
      "ios": "nativescript.vue.autocomplete",
      "android": "nativescript.vue.autocomplete"
    },
    "tns-android": {
      "version": "5.3.1"
    },
    "tns-ios": {
      "version": "5.3.1"
    }
  },
  "dependencies": {
    "@vue/devtools": "^5.0.6",
    "axios": "^0.18.0",
    "nativescript-accordion": "^6.0.0-beta.2",
    "nativescript-background-fetch": "^1.2.1",
    "nativescript-calendar": "^2.0.1",
    "nativescript-contacts": "^1.5.6",
    "nativescript-email": "^1.5.3",
    "nativescript-fonticon": "^2.0.0",
    "nativescript-localstorage": "^2.0.0",
    "nativescript-material-icons": "^1.0.3",
    "nativescript-messenger": "^1.2.0",
    "nativescript-modal-datetimepicker": "^1.2.0",
    "nativescript-oauth2": "^1.4.2",
    "nativescript-phone": "^1.4.0",
    "nativescript-socketio": "^3.2.1",
    "nativescript-toasty": "^1.3.0",
    "nativescript-ui-autocomplete": "^4.0.0",
    "nativescript-ui-dataform": "^4.0.0",
    "nativescript-ui-sidedrawer": "^4.3.1",
    "nativescript-vue": "^2.0.0",
    "nativescript-vue-devtools": "^1.2.0",
    "tns-core-modules": "^5.4.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.9.0",
    "nativescript-dev-webpack": "next",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "terser-webpack-plugin": "^1.1.0",
    "vue": "^2.6.10",
    "vue-loader": "^15.2.6",
    "webpack": "^4.16.4",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.3.1"
  }
}
```

### Please tell us how to recreate the issue in as much detail as possible.
Please attempt to give the same CSS properties available to the native TextField component to the RadAutoCompleteTextView component. (I.E. background-color, font-size, border-color, etc. . .)

Thank you in advance for addressing this issue!

**Comment by tgpetrov** [comment]
@keithgulbro 
The CSS Support for RadAutoCompleteTextView is implemented in nativescript-ui-autocomplete@5.1.0
Here are the docs and examples:
* NS Core - [docs](https://docs.nativescript.org/ui/components/AutoCompleteTextView/autocomplete-getting-started#apply-css), [example](https://github.com/NativeScript/nativescript-ui-samples/tree/master/autocomplete/app/examples/css)
* NS with Angular - [docs](https://docs.nativescript.org/angular/ui/ng-components/ng-AutoCompleteTextView/getting-started#apply-css), [example](https://github.com/NativeScript/nativescript-ui-samples-angular/tree/master/autocomplete/app/examples/css)
* NS with Vue - [docs](https://docs.nativescript.org/vuejs/ns-ui/AutoCompleteTextView/getting-started#apply-css), [example](https://github.com/NativeScript/nativescript-ui-samples-vue/tree/master/autocomplete/app/examples/CssStyle)
