### ISSUE TITLE
Donut Chart Disappear When Legend set to position bottom

### ISSUE THREAD

**Issue by sylvester-etronix** [NativeScript/nativescript-ui-feedback#1139]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Tell us about the problem
I am developing an application which uses RadPieChart and DonutSeries. The donut chart is contain many legend label and text is long, so i need put on bottom. When put on bottom, the chart is disappear.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
nativescript-ui-chart 4.0.2
 tns-core-modules: 5.2.2
tns Antroid platform 5.2.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the playground, provided below.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://play.nativescript.org/?template=play-ng&id=BUuI4d&v=3

![Screenshot_2019-05-30-11-43-19-52](https://user-images.githubusercontent.com/45072247/58607044-910f0580-82d0-11e9-87b3-91329cd1ffff.png)

**Comment by tsonevn** [comment]
Hi @sylvester-etronix,
You need to specify the height of the RadPieChart's container. For example:
```
<ScrollView>
    <StackLayout height="1000" class="dashboard2">
        <RadPieChart allowAnimation="true">
            <DonutSeries tkPieSeries selectionMode="DataPoint" expandRadius="0.4"
                outerRadiusFactor="1" innerRadiusFactor="0.3" valueProperty="Quantity"
                legendLabel="Operation" showLabels="true" [items]="source"
                showPercentage="false">
                <PointLabelStyle tkDonutLabelStyle margin="0" fontStyle="Bold"
                    textSize="10"></PointLabelStyle>
            </DonutSeries>
            <RadLegendView tkPieLegend position="Bottom" title="Operation"
                width="100" enableSelection="true" titleSize="10"></RadLegendView>
        </RadPieChart>
    </StackLayout>
</ScrollView>
```
Check out also the example [here](https://play.nativescript.org/?template=play-ng&id=BUuI4d&v=4)

**Comment by sylvester-etronix** [comment]
Can i change the legend font size?
