### ISSUE TITLE
How to implement RadListView `itemSelecting`?

### ISSUE THREAD

**Issue by jannomeister** [NativeScript/nativescript-ui-feedback#1140]
Is there any example I missed out on implementing `itemSelecting` event? because the only available examples are `itemSelected` and `itemDeselected`.

Because there are some items in the RadListView that should not be selected.

**Comment by tsonevn** [comment]
Hi @jannomeister,
Indeed there is no example for the for`itemSelecting` event.  I will mark it as `docs needed` issue and will add such an example.
Meanwhile:
```HTML
<RadListView row="0" [items]="dataItems" selectionBehavior="Press" (itemSelecting)="onItemSelecting($event)" >
.......
</RadListView>
```
```TypeScript
public onItemSelecting(args: ListViewEventData){
        console.log(`Item selecting, ${args.index}`)
    }
```

**Comment by jannomeister** [comment]
@tsonevn thanks for the response, but is there a way to prevent the item to be selected via `itemSelecting` event?

**Comment by jannomeister** [comment]
I finally found the solution.

thanks to this link: https://www.telerik.com/forums/how-to-select-some-items-of-radlistview-by-default-on-load

I'll leave the code snippet here so someone can see the solution on how to disable selection on specific items.

```
onItemSelecting(args: ListViewEventData) {
        const listview = args.object as RadListView;

        if (args.index < 5) {
            args.returnValue = false;
        }
 }
```
