### ISSUE TITLE
RLV with ObservableArray passes undefined to the itemTap event handler

### ISSUE THREAD

**Issue by msaelices** [NativeScript/nativescript-ui-feedback#1141]
### Tell us about the problem
_If we use an ObservableArray for the items data and we add an `itemTap` event handler, it will pass `undefined` in the `e.item` attribute_

### Which platform(s) does your issue occur on?
_Both_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** 6.3.1
- **CLI:** 5.3.1
- **Cross-platform modules:** 5.3.1
- **Runtime(s):** 5.4.0

### Please tell us how to recreate the issue in as much detail as possible.

Create a sample app with a page component like this:

```
import { ObservableArray } from 'tns-core-modules/data/observable-array';

const getObservableList = () => {
  return new ObservableArray([0, 1, 2]);
};

export default {
  template: `
  <Page>
    <StackLayout>
      <RadListView for="r in currentList"
                   @itemTap="onItemTap">
        <v-template>
          <Label :title="r" />
        </v-template>
      </RadListView>
    </StackLayout>
  </Page>
  `,
  data() {
    return {
      currentList: getObservableList(),
    };
  },
  methods: {
    onItemTap ({ item }) {
      console.log(`Item tapped: ${item}`);
    },
  },
};
```

**Comment by zbranzov** [comment]
Released in version 6.3.2
