### ISSUE TITLE
RadListView Header gets renderes randomly on iOS when grouping is enabled

### ISSUE THREAD

**Issue by jonasjensen-brolstark** [NativeScript/nativescript-ui-feedback#1145]
### Tell us about the problem
If i have a list with both a header and grouping enabled, the header get renderes randomly around in the list when i scroll through it. 
I expect the header always to be at the top of the list.

### Which platform(s) does your issue occur on?
iOS (i have only tested on iOS 12.2)

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** 6.3.0
- **CLI:** playground
- **Cross-platform modules:** 5.4.0
- **Runtime(s):** playground

### Please tell us how to recreate the issue in as much detail as possible.
Sample: [https://play.nativescript.org/?template=play-ng&id=Z2CMwU&v=7](https://play.nativescript.org/?template=play-ng&id=Z2CMwU&v=7)

1. Scroll through the list
2. See the header get rendered randomly in the list

Working as expected when: 
1. remove the `[groupingFunction]="myGroupingFunc"` binding.
2. Scroll through the list
3. The header is now acting as expected

**Comment by zbranzov** [comment]
Released in nativescript-ui-listview@6.4.0
