### ISSUE TITLE
Tapable row

### ISSUE THREAD

**Issue by miloandco** [NativeScript/nativescript-ui-feedback#1146]
Is there any way to make a row tapable? Having white text field on a white background, makes it hard to tap to focus the field.

**Comment by tsonevn** [comment]
Hi @miloandco,
You can use [tap](https://docs.nativescript.org/ui/ns-ui-widgets/gestures#tap) event. You can attach the event to the needed View. For further `How to` related questions, please use our StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript). This thread is used for bug reporting and feature requests.
