### ISSUE TITLE
Textcolor of RadDataForm Listpicker entries cannot be changed

### ISSUE THREAD

**Issue by Naxos84** [NativeScript/nativescript-ui-feedback#1148]
### Tell us about the problem
I am having a DatePicker and a ListPicker in RadDataForm. I need (the selection entries)  of them to have a different color than black. For DatePicker I already found a solution to set the color to green. But this does not work for the ListPicker Editor.

Sidenote: The provided example for a plain ListPicker works with the CSS Property color.

### Which platform(s) does your issue occur on?
iOS 12.2

### Please provide the following version numbers that your issue occurs with:
- "nativescript-ui-dataform": "version": "4.0.0",
- **CLI:** 5.4.0
- **Cross-platform modules:** 5.3.1
- **Runtime(s):** 5.3.1

### Please tell us how to recreate the issue in as much detail as possible.
1. ~https://play.nativescript.org/?template=play-ng&id=Nj15Dj&v=2~
2. open Birth Date --> text is green as expected
3. open My Rating --> text is black but should be green

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
See playground link.

**Comment by nmongiya** [comment]
You need to use setValueForKeyPathmethod e.g.
 coreEditor.subviews[0].setValueForKeyPath(colorWhite.ios, 'textColor');
I have updated the playground as well.  We can close this ticket now.

**Comment by Naxos84** [comment]
No this can not be closed, cause I made a mistake.

Obviously I forgot to save the latest version of my playground example.
I already used "setValueForKey" for my DatePicker and that seems to work just fine.
My Problem is the Picker for "My Rating"

The selectable values for "My Rating" should also be green.
https://play.nativescript.org/?template=play-ng&id=Nj15Dj&v=5

**Comment by Naxos84** [comment]
I found a solution thanks to the Nativescript-Example App.
See: https://stackoverflow.com/q/56472009/3157899 for my answer
