### ISSUE TITLE
RadListView custom group sorting with template not working when enableCollapsibleGroups="true" 

### ISSUE THREAD

**Issue by mandar-bhong** [NativeScript/nativescript-ui-feedback#1149]
RadListView custom group filter but after use enableCollapsibleGroups="true" that time not work

[here example](https://play.nativescript.org/?template=play-ng&id=KCpViw&v=18)

we have both required grouping collapsible and custom group filter how to solve issue

**Comment by tsonevn** [comment]
Duplicate of https://github.com/NativeScript/nativescript-ui-feedback/issues/1102
