### ISSUE TITLE
[RadListView] Crash on swipe in Nativescript-Vue

### ISSUE THREAD

**Issue by tommag21** [NativeScript/nativescript-ui-feedback#1157]
### Tell us about the problem
In a NativeScript-Vue app, swiping a reused cell in a RadListView causes the app to crash. Seen on an iPhone 6s emulator and a real iPhone Xs Max

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
nativescript-ui-listview: 6.3.2 (same problem with 5.1.1)
CLI: 5.4.0
Cross-platform modules: ^5.4.2
iOS runtime: 5.4.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application
2. Navigate to a page with a RadListView
3. Start swiping every item
4. Scroll to items outside the screen
5. Swipe some items until crash: `JS ERROR TypeError: undefined is not an object (evaluating 'owner._realizedCells.get(cell.tag).view')`

As in [this closed issue](https://github.com/NativeScript/nativescript-ui-feedback/issues/186), the workaround of user **kssfilo** solves this for now.

**Comment by tsonevn** [comment]
HI @tommag21,
I tested the described scenario with our [nativescript-ui-samples](https://github.com/NativeScript/nativescript-ui-samples/blob/master/listview/app/examples/swipe-actions/swipe-actions-page.xml) example, however, was unable to recreate a similar problem. On that matter can you provide some more info about the issue and the device that you are using for testing? It will help if you can send us a sample project, that will help us to reproduce the issue.

**Comment by tommag21** [comment]
Sorry, I'm unable to reproduce the issue too. I carried on the development and, as of today, the bug doesn't show up anymore. If it does, I will report it and keep a snapshot.
