### ISSUE TITLE
Colour of tokens in AutoCompleteTextView

### ISSUE THREAD

**Issue by joshcomley** [NativeScript/nativescript-ui-feedback#1158]
## Please, provide the details below:
On the [overview page](https://docs.nativescript.org/ui/professional-ui-components/AutoCompleteTextView/overview), you have some screenshots with colourful tokens:

![image](https://user-images.githubusercontent.com/820534/59950545-2a63ae80-946e-11e9-8ccd-1e49b48bb872.png)
![image](https://user-images.githubusercontent.com/820534/59950554-32235300-946e-11e9-9043-445def51bef7.png)

### Tell us about the problem
I cannot find any such example in the examples app, and any documentation indicating how to achieve this.

If it is not possible, then why is it the primary screenshot on the overview page?

Also there is [this issue](https://github.com/NativeScript/nativescript-ui-feedback/issues/328), but it is almost two years old with no movement whatsoever.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- nativescript-ui-autocomplete - 4.1.0

### Please tell us how to recreate the issue in as much detail as possible.
NA

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
NA

**Comment by tsonevn** [comment]
HI @joshcomley,
Currently, setting up the color for the token is not supported. Regarding that, I would suggest keeping track of the issue https://github.com/NativeScript/nativescript-ui-feedback/issues/328  for more info.
