### ISSUE TITLE
[iOS] Setting swipe template using `tkListItemSwipeTemplate` causes the RadListView to be retained in memory after GC

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-ui-feedback#1167]
### Tell us about the problem
If you set a template for the swipe items (`tkListItemSwipeTemplate` on Angular), if you call GC theRadListView native instances (TKListView) are not cleared on iOS.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** (the version of nativescript-ui-* in the `package.json`)
- **CLI:** (run `tns --version` to fetch it)
- **Cross-platform modules:** (the version of tns-core-modules in the `package.json`)
- **Runtime(s):** (the `"tns-android"` and `"tns-ios"` properties in the `package.json`)

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the attached application
2. Start XCode instruments and profile the deployed app (`radlistviewmemoryleakmaster2`)
3. Press "Navigate to Test Component` > Back, repeat a couple of times.
4. When on the home component press "Collect Garbage" a couple of times (note that on simulators it is possible that single GC trigger will not actually work)
5. Notice the memory not lowering, and if you search for TKListView you will notice multiple instances of it left over.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
You need to have a declared `*tkListItemSwipeTemplate` in the `RadListView`. Simply removing that element resolves this issue.

```
<RadListView id="listView" row="1" [items]="items" height="500" swipeActions="false" (itemSwipeProgressStarted)="onSwipeCellStarted($event)">
    <ng-template tkListItemTemplate let-item="item">
        <Label [text]="'item ' + item"></Label>
    </ng-template>
    <GridLayout columns="*, auto" *tkListItemSwipeTemplate>
        <Button row="0" col="1" text="test" id="test" verticalAlignment="center"
            (tap)="onTestButtonTap($event)"></Button>
    </GridLayout>
</RadListView>
```

[radlistview-memory-leak-master 2.zip](https://github.com/NativeScript/nativescript-ui-feedback/files/3392103/radlistview-memory-leak-master.2.zip)

Additional testing projects:
- Vanila {N}:
[memory-test.zip](https://github.com/NativeScript/nativescript-ui-feedback/files/3381872/memory-test.zip)
- Angular {N}:
[memory-test-ng.zip](https://github.com/NativeScript/nativescript-ui-feedback/files/3381874/memory-test-ng.zip)
- Angular {N} with custom comp in templates:
[memory-test-ng-custom-comp.zip](https://github.com/NativeScript/nativescript-ui-feedback/files/3385759/memory-test-ng-custom-comp.zip)

**Comment by tgpetrov** [comment]
Released with [nativescript-ui-listview@7.0.1](https://github.com/NativeScript/nativescript-ui-feedback/blob/master/releases/listview.md#701-2019-july-17)
