### ISSUE TITLE
how to submit form 

### ISSUE THREAD

**Issue by prashantnirgun** [NativeScript/nativescript-ui-feedback#1177]
Hi 
This is Prashant here I am new to Nativescript Vue I find all the examples are of typescript and I am not using the typescript didn't get reply on slack. I don't even find the example on google. 
I understa how to create the form. But how do I submit the form which method or event is called. Submit Reset Button is missing find it lost

✔ Component nativescript has 5.4.2 version and is up to date.
✔ Component tns-core-modules has 5.4.3 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.
⚠ Update available for component tns-ios. Your current version is 5.4.0 and the latest available version is 5.4.2.

**Comment by tsonevn** [comment]
Check out the example [here](https://github.com/NativeScript/nativescript-ui-samples-vue/blob/master/dataform/app/examples/ValidationEvents.ts).
Keep in mind that this repository must be used only for bug reporting and logging new feature requests. For further questions, please use our [StackOverflow thread here](https://stackoverflow.com/questions/tagged/nativescript).
