### ISSUE TITLE
Can we change DatePicker country from RadDataForm ?

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-ui-feedback#1180]
@Loown commented on [Tue Jul 16 2019](https://github.com/NativeScript/NativeScript/issues/7530)

Hi,

I'm trying to find out a solution to output french translation of the chosen date of a user.

When someone selects a date he gets this output : 

> Tue, 17.06

Actually I'm french and I would have something like this : 

> Mardi 16 Juillet

Is there a feature to change that behavior?

I'm new and still learning so be kind !

**Comment by tsonevn** [comment]
Hi @Loown,
The language of the DataForm date will be the same as the default device language. On that matter, if you change your device language to french, the date language will be changed as well. For further questions, you can use our [StackOverflow thread here.](https://stackoverflow.com/questions/tagged/nativescript)
