### ISSUE TITLE
RadListView Swipe actions and items reorder do not work together in Android 

### ISSUE THREAD

**Issue by tbozhikov** [NativeScript/nativescript-ui-feedback#1184]
### Tell us about the problem
I cannot get swipe actions and items reorder to work together in RadListView. See this [playground app](https://play.nativescript.org/?template=play-tsc&id=8mTU4X&v=2).

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- "nativescript-ui-listview": 7.0.0,
- **CLI:** 6.0.0
- **Cross-platform modules:** 6.0.1,
- **Runtime(s):** 6.0.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application
2. Try to hold and drag to reorder - works
3. Try to swipe an item - should work, but in Android, it doesn't

To reproduce in RLV demos:
1. Open `multiple-operations-with-swipe-page.xml`
2. Set `itemReorder="true"` and `reorderMode="HoldAndDrag"` to the `RadListView` tag
3. Run the `demo` project

**Workaround**: if I change `android:swipeActions` to `android:itemSwipe`, swipe works. However `itemSwipe` property is deprecated in RLV, so this should be fixed.

**Comment by DimitarTodorov** [comment]
Issue fixed in 7.0.2 of nativescript-ui-listview
