### ISSUE TITLE
Chart animations are laggy on iOS 13 beta

### ISSUE THREAD

**Issue by zbranzov** [NativeScript/nativescript-ui-feedback#1191]
### Tell us about the problem
Chart animations are laggy on iOS 13 beta and the visualisation of the chart is not smooth.
A simple demo https://screencast.com/t/VJy5oDQEPG even though it does not clearly represent the issue.

### Which platform(s) does your issue occur on?
_iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** 6.0
- **CLI:** 6.0
- **Cross-platform modules:** 6.0
- **Runtime(s):** 6.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Use demo examples

**Comment by zbranzov** [comment]
Using latest Xcode 11 beta and iOS simulator 13, the chart continue to be lagging. On iOS 13 device it works fine

**Comment by niksudan** [comment]
Recently upgraded to Xcode 11 (it's out of beta now) and have been using simulators running iOS 13 - they still appear to be lagging.
