### ISSUE TITLE
Listview does not work in iOS 13 beta

### ISSUE THREAD

**Issue by zbranzov** [NativeScript/nativescript-ui-feedback#1193]
### Tell us about the problem
Listview examples are blank on iOS 13.

### Which platform(s) does your issue occur on?
_iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** 6.0
- **CLI:** 6.0
- **Cross-platform modules:** 6.0
- **Runtime(s):** 6.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Use demo examples

**Comment by elena-p** [comment]
Duplicate of https://github.com/NativeScript/nativescript-ui-feedback/issues/1160
