### ISSUE TITLE
DataForm: Apply different CSS for editors on focus

### ISSUE THREAD

**Issue by tgpetrov** [NativeScript/nativescript-ui-feedback#1202]
### Tell us about the problem
Currently it is not possible to apply different CSS while an editor is on focus, similarly to the way you can with TextField-s, for example.

**Comment by DimitarTodorov** [comment]
АC:
1. Add e2e tests for the examples
2. Styles should be applied correctly on android and on iOS
3. Styles applied from xml/html as well

**Comment by DimitarTodorov** [comment]
Issues:

- [ ] When keyboard pop-ups the action bar hides and scrolling up doesn't show the cation bar again. It is unreachable. Attached screenshot. 
<img width="478" alt="Screenshot 2019-08-15 at 13 34 40" src="https://user-images.githubusercontent.com/7533292/63090365-ae647f00-bf63-11e9-9e0c-21372d4bbbf9.png">

**Comment by DimitarTodorov** [comment]
- [ ] CSS styles are not applied when app is build with webpack and `--env.uglify` flag.

**Comment by DimitarTodorov** [comment]
Feature is available with 5.1.0 of nativescript-ui-dataform
