### ISSUE TITLE
[RadDataForm] list of value options for value providers using Vue

### ISSUE THREAD

**Issue by scebotari66** [NativeScript/nativescript-ui-feedback#1208]
### Tell us about the problem
The docs [specify](https://docs.nativescript.org/vuejs/ns-ui/DataForm/dataform-editors-providers#raddataform-values-providers) that there are four options you can use to set the values provider:

> Here are the options to provide the list of values:
> 
> Array with Values
> Map with Values and the Labels for Them
> Array with Key-Label Pairs
> Array with Custom Objects

It seems that only the first type (array with values) is supported for `"nativescript-ui-dataform/vue"`.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** 5.0.0
- **Cross-platform modules:** 6.0.6
- **Runtime(s):** `"tns-android"`: 6.0.0, `"tns-ios"`: 6.0.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the playground application
2. Notice that only the first picker field ("Array With Values") renders the values as expected. Note: for the "Array with Custom Objects" the `valuesProvider` config is commented out because it raises the following exception:

> An uncaught Exception occurred on "main" thread.
> Calling js method onCreateView failed
> Error: java.lang.ClassCastException: org.json.JSONObject cannot be cast to org.json.JSONArray

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://play.nativescript.org/?template=play-vue&id=MqEAeX

**Comment by msaelices** [comment]
@scebotari66 Actually all the options for `valuesProvider` work. See this sample which shows how you can define them: https://github.com/NativeScript/nativescript-ui-samples-vue/pull/127

**Comment by scebotari66** [comment]
Thanks @msaelices for the sample. Indeed, like that it works. But this seems more like a workaround to me. In the documentation examples the `valuesProvider` option is specified in form metadata via `propertyAnnotations`, which still does not work. Is the documentation outdated or we are still looking at a bug here?

**Comment by msaelices** [comment]
@scebotari66 I guess that the `propertyAnnotations` are not capable of handling all the customization options which have the template markup. Probably @elena-p or some other core members are able to answer you better than me.

**Comment by tgpetrov** [comment]
@scebotari66 The [documentation article](https://docs.nativescript.org/vuejs/ns-ui/DataForm/dataform-editors-providers) includes a sample where the `valuesProvider` which is part of the `propertyAnnotation` is in the form of array of strings. It is the only supported format for `valuesProvider` when it is included in the metadata (propertyAnnotations).

While the documentation doesn't explicitly state it, the other samples are showing how to use other formats of `valuesProvider`, but they are not part of the metadata and are only intended to be used as in the example @msaelices sent you.

There is a feature request [here](https://github.com/NativeScript/nativescript-ui-feedback/issues/369) for supporting the other formats of `valuesProvider` as part of the metadata, but it is not yet implemented.

**Comment by scebotari66** [comment]
Thanks, @msaelices and @tgpetrov for the clarifications. I think the docs should mention this somehow. As NativeScript newbie, I started using `RadDataForm` with editors custmozied via `propertyAnnotations` because this is the way you see it in the [documentation](https://docs.nativescript.org/vuejs/ns-ui/DataForm/dataform-editors#usage). And then you want to customize the `valuesProvider` and you are lost.

**Comment by tgpetrov** [comment]
@scebotari66 Yes we should clarify this in the docs.

**Comment by mannok** [comment]
Anyone is going to finish this on Vue? DataForm is a very important feature in mobile. If the RadDataForm cannot fully work with these frontend framework. It may affect the development cycle so much.
