### ISSUE TITLE
Time Picker RadDataform

### ISSUE THREAD

**Issue by avinashbora** [NativeScript/nativescript-ui-feedback#1211]
How to assign value to Timepicker in raddataform in native script

**Comment by avinashbora** [comment]
<RadDataForm #frmWorkLog [source]="worklog" [metadata]="worklogMetadata"  (propertyCommitted)="onPropertyCommitted($event)">             
<TKEntityProperty tkDataFormProperty name="action" index="6" [valuesProvider]="actionList">
                        <TKPropertyEditor tkEntityPropertyEditor type="Picker"></TKPropertyEditor>
                </TKEntityProperty>
 </RadDataForm>

**Comment by tsonevn** [comment]
HI @avinashbora,
Check out the [example here ](https://github.com/NativeScript/nativescript-ui-samples-angular/tree/d6f6999f7c0774c227cd0bd9a79f5d7ea017dc58/dataform/app/examples/editors/datetime) where it is demonstrated how to set up the TimePicker editor.
