### ISSUE TITLE
[RadDataForm] empty decimal editor keeps the last removed digit as value using Vue

### ISSUE THREAD

**Issue by scebotari66** [NativeScript/nativescript-ui-feedback#1220]
### Tell us about the problem
I try to use a `Decimal` editor in my RadDataForm and there is a problem when I completely remove the value of the field. The bound value keeps the last remove digit.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** 5.0.0
- **Cross-platform modules:** 6.0.6
- **Runtime(s):** `"tns-android"`: 6.0.0, `"tns-ios"`: 6.0.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the playground application
2. Notice the label below the field is bound to the field's value
3. Completely remove the field's value and you will notice that the label still has a value (the last removed digit)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://play.nativescript.org/?template=play-vue&id=4O7xuk&v=2

**Comment by scebotari66** [comment]
This is a pretty unpleasant bug. Does any workaround comes to your mind while we wait for the fix? 🤔

**Comment by DimitarTodorov** [comment]
The fix is available with 5.1.1 of nativescript-ui-dataform which is now published to npm.
