### ISSUE TITLE
RadSideDrawer automatically closes if tapped or scrolled during slide transition

### ISSUE THREAD

**Issue by prokkyb** [NativeScript/nativescript-ui-feedback#1222]
### Tell us about the problem
RadSideDrawer closes if you scroll or tap anything inside it while it's still opening (during slide transition).

### Which platform(s) does your issue occur on?
Android; have not had a chance to test a physical iOS device yet but it doesn't happen with the iOS emulator.

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** nativescript-ui-sidedrawer 7.0.0
- **CLI:** 6.0.3
- **Cross-platform modules:** 6.0.7
- **Runtime(s):** Android: 6.0.2, iOS: 6.0.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Open RadSideDrawer
2. While RadSideDrawer is sliding, tap or scroll on the RadSideDrawer
3. RadSideDrawer closes (slides back to side of screen)

**Comment by tsonevn** [comment]
Hi @prokkyb,
I tested the described scenario with [our sample project ](https://github.com/NativeScript/nativescript-ui-samples/tree/master/sidedrawer/app/examples/getting-started)on both(Android and iOS), however, was unable to recreate such a problem. Can you check if you will be able to recreate the issue with the attached sample?
If not, can you send us a sample project, that can be used for reproducing the issue?

**Comment by prokkyb** [comment]
@tsonevn I tested this out with the sample project as well as the _template-drawer-navigation-ng_ template (which we based our app on), and I was not able to reproduce the issue either. I traced it back to a workaround we used for [this issue](https://github.com/NativeScript/nativescript-ui-feedback/issues/1024). Thank you for checking on this. I'll close this issue.
