### ISSUE TITLE
No method to center an element inside a RadListView with an explicit height !! 

### ISSUE THREAD

**Issue by devToudert** [NativeScript/nativescript-ui-feedback#1223]
Can not center an elements of a RadViewList in the middle of the screen in a nativescript-angular app. I tried several methods without result: FlexBoxLayout, horizontalAlignment and verticalAligmnent, inline css, css display flex..

See my code in the Playground: https://play.nativescript.org/?template=play-ng&id=acMEE0&v=2
ScreenShot of what I want to have: https://ibb.co/tXq9QqV
Asked for in stackoverflow: https://stackoverflow.com/questions/57656400/center-items-in-radlistview-in-nativescript

**Comment by tsonevn** [comment]
Hi @devToudert 
In your case, you can use `FlexboxLayout` while setting to the `alignSelf` to `center` for the Label. Check out the sample [here](https://play.nativescript.org/?template=play-ng&id=acMEE0&v=4).
