### ISSUE TITLE
[SideDrawer] drawerTransition is ignored since 7.0.1

### ISSUE THREAD

**Issue by acivier-serial** [NativeScript/nativescript-ui-feedback#1225]
**Environment**
 - CLI: 6.0.3
 - Cross-platform modules: 6.07
 - Android Runtime: 6.0.0
 - iOS Runtime: 6.0.1
 - Plugin(s):
   - nativescript-ui-sidedrawer: 7.0.1
  - Angular: 8.0.0

**Describe the bug**
When passing a transition to the RadSideDrawer  the default transition is still played. This bug appear in the 7.0.1 nativescript-ui-sidedrawer release.

In this case i'm using the PushTransition:
```typescript
    ngOnInit(): void {
        this._sideDrawerTransition = new PushTransition();
    }
```
```html
<RadSideDrawer [drawerTransition]="sideDrawerTransition">
<!-- ... -->    
</RadSideDrawer>
```

![2019-09-03 11-31-47 2019-09-03 11_32_06](https://user-images.githubusercontent.com/50982494/64161804-88cde580-ce3e-11e9-8739-005198248ee6.gif)

**To Reproduce**
Launch the [issue-drawer-animation-nativescript repo](https://github.com/acivier-serial/issue-drawer-animation-nativescript) in a simulator, then toggle the side drawer.

**Expected behavior**
The new transition applied should be effective.

**Sample project**
https://github.com/acivier-serial/issue-drawer-animation-nativescript

Thanks you !

**Comment by zbranzov** [comment]
The fix is released in nativescript-ui-sidedrawer@7.0.2
