### ISSUE TITLE
Raddataform NativeScript

### ISSUE THREAD

**Issue by avinashbora** [NativeScript/nativescript-ui-feedback#1227]
I have to put a submit button in reddata form, when i did this, then submit button is not visible to UI, But when i take submit button outside the raddata form, it is working good. Is there any provision to put submit button inside raddata form?

**Comment by tsonevn** [comment]
HI @avinashbora,
The submit button should be outside the RadDataForm. For further questions, please use the StackOverflow [thread here.](https://stackoverflow.com/questions/tagged/nativescript)
