### ISSUE TITLE
The padding applied to AutoComplete is not correct

### ISSUE THREAD

**Issue by tgpetrov** [NativeScript/nativescript-ui-feedback#1234]
### Tell us about the problem
The padding applied to RadAutoComplete through CSS is applied on top of the defaults instead of changing them. This makes it impossible to remove the default padding.

### Which platform(s) does your issue occur on?
Both

### Please tell us how to recreate the issue in as much detail as possible.
1. To reproduce, in autocomplete-getting-started-page.xml in the demo app, change this line:
```
<au:RadAutoCompleteTextView id="autocomplete" items="{{ dataItems }}" displayMode="Tokens"/>
```
with:
```
<GridLayout columns="*,*">
        <StackLayout>
                <TextField style="padding: 16; background: green" />
        </StackLayout>
        <StackLayout column="1">
                <au:RadAutoCompleteTextView items="{{ dataItems }}" style="padding: 16; background: red"/>
        </StackLayout>
</GridLayout>
```
2. Run the app and type some text in both fields. Observe the difference between the two:
![image](https://user-images.githubusercontent.com/6085251/65041885-67055000-d960-11e9-85db-8b770602bcb4.png)

3. The expected behavior is that they look the same, since they both have padding 16:
![image](https://user-images.githubusercontent.com/6085251/65041986-95832b00-d960-11e9-9ae3-724da262c619.png)

**Comment by zbranzov** [comment]
Released in nativescript-ui-autocomplete@5.1.1
