### ISSUE TITLE
Nativescript to apple store error plugin

### ISSUE THREAD

**Issue by Farjallahmed** [NativeScript/nativescript-ui-feedback#1240]
Hi developers, i am trying to publish my app to apple store but always i get the same problem 
cam any body help ? thank you 

> No suitable application records were found. Verify your bundle identifier 'org.cocoapods.FLAnimatedImage' is correct.

**Comment by tsonevn** [comment]
Hi @Farjallahmed,
Make sure that you have created an app in [Itunes Connect](https://itunesconnect.apple.com/login), before uploading the project. Keep in mind that this repository is used only for a feature request and bug reports related to NativeScript UI components. For FR and bugs connected with NativeScript itself, you can use [this repository](https://github.com/NativeScript/NativeScript/issues). For other problems or question, please use [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript).
