### ISSUE TITLE
[RadListView]  No selection color if itemTemplate is set to 'transparent'

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-ui-feedback#1249]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Tell us about the problem
If you set the `backgroundColor="transparent"` on the first element of the `itemTemplate`, there will not be any selection box, or if you sety `itemSelectedBackgroundColor` it wont be used. 

### Which platform(s) does your issue occur on?
Android: Above 22 API lv

**Comment by zbranzov** [comment]
The fix is released in nativescript-ui-listview@8.0.0
