### ISSUE TITLE
[CHART] Allow Palette to to receive colours / styling from CSS

### ISSUE THREAD

**Issue by Eonfuzz** [NativeScript/nativescript-ui-feedback#1252]
I work on a project with multiple applications using the same / similar codebase. Allowing the palette styling to be pulled from css / the applied styling would be a genuine godsend.

**Comment by tsonevn** [comment]
Hi @Eonfuzz,
We are working on providing support for this feature. We've made [this tracking issue](https://github.com/NativeScript/nativescript-ui-feedback/issues/1255) about the feature. You can keep track on the issue for further info and to comment it, if some additional info is required.
