### ISSUE TITLE
SideDrawer 7.0.2 breaks scrolling/tapping

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/nativescript-ui-feedback#1262]
Just upgraded from `7.0.0` to `7.0.2` of `nativescript-ui-sidedrawer`. Upon opening the drawer on iOS, I can no longer tap on any items, nor can I scroll the list.

Here is the repo that you can use to reproduce (though it's using `7.0.0` right now): 

https://github.com/rdlauer/plum

**Comment by VladimirAmiorkov** [comment]
This has been fixed in `nativescript-ui-sidedrawer@7.0.3`
