### ISSUE TITLE
Deprecated property on ui-listview can be the cause of visual issue on iOS

### ISSUE THREAD

**Issue by nuno-morais** [NativeScript/nativescript-ui-feedback#1264]
# Tell us about the problem
We are receiving a console log with a warning message because the lib is using a "deprecated" property. Either than that, some transitions between views are not rendering correctly the list view (given an extra space in some scenarios).

Transition this page:
<img width="395" alt="Screenshot 2019-10-12 at 19 29 42" src="https://user-images.githubusercontent.com/1490250/66706170-7db48200-ed27-11e9-90cb-c41da010efad.png">

To another:
<img width="388" alt="Screenshot 2019-10-12 at 19 30 38" src="https://user-images.githubusercontent.com/1490250/66706176-8907ad80-ed27-11e9-90cf-f5338dec8d48.png">

But it should appear this way:
<img width="392" alt="Screenshot 2019-10-12 at 19 31 30" src="https://user-images.githubusercontent.com/1490250/66706186-96bd3300-ed27-11e9-835c-25f31d69c28f.png">

**Current warning message:**
CONSOLE LOG file:///node_modules/nativescript-ui-listview/ui-listview.js:1036:0: Warning: When using 'listViewLayout' of type ListViewGridLayout it is recommended to set it's 'itemHeight' property.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** `"nativescript-ui-listview": "^7.1.0"`
- **CLI:** (run `tns --version` to fetch it): **6.1.0**
- **Cross-platform modules:** `"tns-core-modules": "^6.1.1",`
- **Runtime(s):** `"tns-ios" > "version": "6.1.1"`

**Comment by tsonevn** [comment]
Hi @nuno-morais,
I've checked [our sample application](https://github.com/NativeScript/nativescript-ui-samples/tree/master/listview). However, I was unable to recreate a problem with the RadListView component. Can you send us the project or sample one, where the issue that you are facing can be reproduced?
