### ISSUE TITLE
Can't modify border for autocomplete

### ISSUE THREAD

**Issue by aranmohyeddin** [NativeScript/nativescript-ui-feedback#1268]
Everything is most recent npm version.
The issue is tested on Android
I'm using nativescript-vue

Here is my css:
```
  RadAutoCompleteTextView {
    border-color: gray;
    border-width: 1;
    margin-bottom: 20;
  }
```

Here is my template:
```
      <RadAutoCompleteTextView
        :items="regions"
        completionMode="Contains"
        @textChanged="textChanged"
      />
```

The problem is that I don't get the border-bottom on IOS since IOS TextFields don't have borders and by background is while so the user won't know where to type. So I'm trying to make the border explicit so as to have consistent UI between IOS and Android.

When I set the border like so, a padding is created below the TextField of the autocomplete, setting padding to 0 didn't help either.

**I just want to have IOS and Android look the same!**
Please just tell me how I can have a persistent gray borderBottom with width of 1px on both IOS and Android.

**Comment by tsonevn** [comment]
HI @aranmohyeddin, 
I tested the described scenario with the RadAutoCompleteTextView component on iOS and Android. However, I was unable to recreate a problem with the border. For your convenience, I am attaching a [sample project](https://play.nativescript.org/?template=play-vue&id=UzfvQ4), where both scenarios are tested(bottom border/ border on all sides).  Please, check the project and make the needed changes which will allow us to reproduce the issue

**Comment by aranmohyeddin** [comment]
I'm really sorry. I played with it more and more just setting and resetting random things like return keyboard type, padding, etc and now it is suddenly working. I will try to reproduce the issue. I will let you know if I can reproduce it.
