### ISSUE TITLE
autocomplete suggest view not displaying correct value

### ISSUE THREAD

**Issue by aldoabazi** [NativeScript/nativescript-ui-feedback#1271]
I am working on a project with nativescript-angular. I use autocomplete in my home component.When i route away from home component, i use back() function to return so home component is cached(because i have a map in home component and don't want to zoom every time i access this component). In Home the autocomplete i use is to redirect map to preferred city.After some time of navigation between components, when i try to type in autocomplete i get icorrect names of city compered with what i type, but the id of the first city i was suggested is the same of the one i started to type

**Comment by tsonevn** [comment]
Hi @aldoabazi,
Can you send us a sample app, where the issue can be reproduced?
