### ISSUE TITLE
Nativescript Listview keeps crashing

### ISSUE THREAD

**Issue by HunterJS-bit** [NativeScript/nativescript-ui-feedback#1282]
### Tell us about the problem
Hi guys I was having problem with Listview not being rendered on IOS13, I have upgraded CLI to v5, but now I have this other problem like Listview is not being properly registered ???
`
file:///app/tns_modules/tns-core-modules/ui/builder/builder.js:238:56: JS ERROR Error: Building UI from XML. @file:///app/views/contacts/contacts.xml:12:13
> Module '/Users/autview/Library/Developer/CoreSimulator/Devices/B1E24EF1-B585-4EA2-86E0-5271F82C0765/data/Containers/Bundle/Application/D93CBB24-3E13-4647-8B5F-CE73E93A5D4A/mobile.app/node_modules/nativescript-ui-listview' not found for element '../node_modules/nativescript-ui-listview:RadListView'.
> Coulld
`

### Which platform(s) does your issue occur on?
_iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** (nativescript-listview) - 7.0.4
- **CLI:**  5.4.2
- **Cross-platform modules:** 4.0.0.
- **Runtime(s):*tns-ios - 4.0.1

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Here is my sample component Im using:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd"
xmlns:lv="../node_modules/nativescript-ui-listview"
xmlns:appHeader="/views/header/"
loaded="ContactsLoaded">
<appHeader:header backButton="true"/>
<GridLayout  rows="auto,*" columns="*">
    <GridLayout row="1" col="0">
        <lv:RadListView items="{{ contacts }}" >
            <lv:RadListView.itemTemplate>
                <StackLayout orientation="vertical">
                    <Label fontSize="20" text="Markooo"/>
                </StackLayout>
            </lv:RadListView.itemTemplate>
        </lv:RadListView>
        <ActivityIndicator class="activity-indicator" busy="{{ isLoading }}" />
    </GridLayout>
</GridLayout>
</Page>
```

and here is my bundle,config

```
if (global.TNS_WEBPACK) {
    //registers tns-core-modules UI framework modules
    require("bundle-entry-points");

    //register application modules
    global.registerModule("main-page", function () { return require("./main-page"); });

    global.registerModule("nativescript-ui-listview", () => require("../node_modules/nativescript-ui-listview"));
}
```

**Comment by tsonevn** [comment]
Hi @HunterJS-bit,
Try to update your project to the latest NativeScript 6 and check if you will be able to recreate the issue. Check out the migrate instruction [here](https://docs.nativescript.org/releases/upgrade-instructions).
