### ISSUE TITLE
`Attr` collision between `nativescript-ui-chart` and `nativescript-material-button`

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-ui-feedback#1296]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Tell us about the problem
Using `nativescript-material-button` in combination with `nativescript-material-core@2.5.3` and `nativescript-ui-chart` causes an build error.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** "nativescript-ui-chart": "7.0.0"
- **CLI:** 6.2.0
- **Cross-platform modules:** 6.2.0
- **Runtime(s):** 6.2.0

**Comment by lini** [comment]
Released in nativescript-ui-chart@7.1.0
