### ISSUE TITLE
[RadListView] Css Element selectors don't work with uglify

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-ui-feedback#1297]
### Tell us about the problem
Css Element selectors don't work with uglify.

### Which platform(s) does your issue occur on?
Tested Android, but may be both.

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** nativescript-ui-listview@8.0.0
- **CLI:** 6.2.0
- **Cross-platform modules:** 6.2.0
- **Runtime(s):** 6.2.0

### Please tell us how to recreate the issue in as much detail as possible.
Steps to reproduce:
```
tns create TestApp --template tns-template-master-detail-ng
Add `.m-r-20{ background-color: red; }` at the end of `TestApp/src/app.android.scss`
tns run android --env.uglify
```
Result:
Red colour is not applied.

**Comment by zbranzov** [comment]
The fix is released in nativescript-ui-listview@8.0.1
