### ISSUE TITLE
The link for 6.0.0 breaking changes is not working

### ISSUE THREAD

**Issue by hmsca** [NativeScript/nativescript-ui-feedback#1303]
As the title says, the link for 6.0.0 breaking changes is not working.

Example: https://github.com/NativeScript/nativescript-ui-gauge/pull/80

**Comment by VladimirAmiorkov** [comment]
Thank you for bringing this to our attention. I updated those Breaking changes sections https://github.com/NativeScript/nativescript-ui-feedback/commit/ab972638754dbfeec7c1f8c31cb4b078a645acc3 .

Regarding the `nativescript-ui-gauge` there are not breaking changes.
