### ISSUE TITLE
RadPieChart pointSelect, pointDeslected events in the wrong order

### ISSUE THREAD

**Issue by quinnban** [NativeScript/nativescript-ui-feedback#1310]
### Tell us about the problem

The RadPieChart component 'pointSelected' event happens before the 'pointDeselected' event, when selecting another point on the pie chart.

### Which platform(s) does your issue occur on?

Android
It works on IOS as intended

### Please provide the following version numbers that your issue occurs with:

{
  "nativescript": {
    "id": "org.nativescript.GrainX",
    "tns-ios": {
      "version": "6.2.0"
    },
    "tns-android": {
      "version": "6.2.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "2.2.1",
    "nativescript-angular": "8.20.3",
    "nativescript-sqlite": "^2.3.3",
    "nativescript-ui-chart": "^7.0.0",
    "nativescript-ui-dataform": "^6.0.0",
    "nativescript-ui-listview": "^8.0.1",
    "nativescript-ui-sidedrawer": "^8.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "6.2.1",
    "zone.js": "~0.9.1"
  },

### Please tell us how to recreate the issue in as much detail as possible.

1. Run Playground
2.Select point on Chart
3. Select another point on chart.
4. Watch console.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

https://play.nativescript.org/?template=play-ng&id=1A9dWg

**Comment by NickIliev** [comment]
@quinnban it seems that this is a specific behavior for the native Android component
