### ISSUE TITLE
RadListView multi template not working

### ISSUE THREAD

**Issue by kryptus36** [NativeScript/nativescript-ui-feedback#1315]
### Tell us about the problem
_Please, ensure your title is less than 63 characters long and starts with a capital
letter._

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** 7.1.0
- **CLI:** (run `tns --version` to fetch it) 6.2.2
- **Cross-platform modules:** 6.2.3
- **Runtime(s):** iOS 6.3.0/android 6.1.2

### Please tell us how to recreate the issue in as much detail as possible.
1. Create a RadListView using multiple templates
2. I can not get it to run the itemTemplateSelector

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```xml
<lv:RadListView row="1" height="100%" items="{{ list }}" itemTemplateSelector="{{ potListTemplate }}">
<lv:RadListView.itemTemplate>
                                    <Label text="{{  template  }}" />
                                </lv:RadListView.itemTemplate>
                                <lv:RadListView.itemTemplates>
                                    <template key="mdate">
                                        <StackLayout orientation="vertical" style.backgroundColor="green">
                                            <Label text="{{ date }}" class='date' />
                                        </StackLayout>
                                    </template>
                                    <template key="promotion">
                                        <StackLayout class='promotion'>
                                            <Label text="{{  title  }}" class='title' textWrap='true' />
                                            <Label text="{{  description  }}" class='description' textWrap='true' />
                                        </StackLayout>
                                    </template>
                                </lv:RadListView.itemTemplates>
                                
                                
                            </lv:RadListView>
```

In my js file I have a simple function inside my view model object (which never fires and the default template is always used and the label shows "mdate"):

```
potListTemplate: function(item, index, items) {
      console.log('template', item);
      return item.template;
    }
```

if I change itemTemplateSelector="mdate" the app crashes .

**Comment by kryptus36** [comment]
scope issue. I needed to use $parents in my binding

**Comment by louislamme** [comment]
> scope issue. I needed to use $parents in my binding

I am using nativescript-vue and experience the same issue of using multiple conditional templates , could you share me more information of your solution? Thanks.

**Comment by kryptus36** [comment]
I am using my listview inside of a nativescript-carousel. So I needed to change the above code to 

```xml
<lv:RadListView row="1" height="100%" items="{{ list }}" itemTemplateSelector="{{ $parents['Carousel'].potListTemplate }}">```

I found this helpful:
https://docs.nativescript.org/core-concepts/data-binding#binding-to-a-parent-binding-context
