### ISSUE TITLE
group using radlistview with only js and not ts

### ISSUE THREAD

**Issue by wuilmerj24** [NativeScript/nativescript-ui-feedback#1316]
I understand that this means is only to report problems or suggest new functions. But how can I create a radlisview grouped with just js and not ts?

**Comment by NickIliev** [comment]
@wuilmerj24 any TypeScript will be converted to JS when executing the `tsc <file-path>` command.

**Comment by wuilmerj24** [comment]
Hi. Thanks for responding and I understand. Already try stackoverflow but no answer.
