### ISSUE TITLE
Calling js method getReorderHandleOverride failed. Type error: cannot read property 'eachChildView' of undefined

### ISSUE THREAD

**Issue by ChangePlaces** [NativeScript/nativescript-ui-feedback#1323]
### Tell us about the problem

I have a radlistview with a reorder mode of drag, along with a handle, and the radlistview also has an onitemtap which navigates to a detail view.

I've noticed when I tap on an item to see the detail, then navigate back (page.frame.goBack), and then start a drag, I get an app crash with the following information

```
An uncaught Exception occurred on 'main' thread. Calling js method getReorderHandleOverride failed. Type error: cannot read property 'eachChildView' of undefined

Stack trace:
ExtendedReorderWithHandlesBehaviour: getReorderHandleOverride(file:///data/data/org.nativescript.notepad/files/app/vendor.js:40300:27
```

I have attempted to catch the itemReorderStarting event to attempt to debug the issue, but the crash occurs before that event is fired.

### Which platform(s) does your issue occur on?
Android 6

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version: 8.0.1
- **CLI:** 6.2.2
- **Cross-platform modules:** 6.2.0
- **Runtime(s):** 6.2.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. tap on an item in the list view,
3. go back
4. begin drag (in mode drag)
5. app crash occurs

**Comment by lini** [comment]
I tried to reproduce the problem with a sample app in the playground - 
https://play.nativescript.org/?template=play-js&id=xetrxL

I did not see any errors when navigating to details and reordering items. Can you give us some working code to reproduce this on our side?

**Comment by ChangePlaces** [comment]
@lini thanks, I made a few minor changes to my code, and haven't seen the problem since. I think it may have been a weird stupid newbie problem so closing!
