### ISSUE TITLE
RadDataForm not appearing on template

### ISSUE THREAD

**Issue by aquinn637** [NativeScript/nativescript-ui-feedback#1331]
### Tell us about the problem
_Please, ensure your title is less than 63 characters long and starts with a capital
letter._
I want to build a form with the RadForms library and I tried to follow the instructions on this website: https://docs.nativescript.org/ui/components/DataForm/dataform-overview#editors

The form is not appearing on the ui.

### Which platform(s) does your issue occur on?
both

### Please provide the following version numbers that your issue occurs with:
{
  "nativescript": {
    "id": "org.nativescript.RadFormsTest",
    "tns-android": {
      "version": "6.1.2"
    },
    "tns-ios": {
      "version": "6.1.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "nativescript-angular": "~8.2.0",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-ui-dataform": "^6.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.1.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "nativescript-dev-webpack": "~1.2.0",
    "typescript": "~3.5.3"
  },
  "gitHead": "1964ea9e8ca1a0518e0d6370781eedcf6c23db42",
  "readme": "NativeScript Application"
}

### Please tell us how to recreate the issue in as much detail as possible.
1. tns run android 
to run it on an Android device

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Here is my repository: https://github.com/aquinn637/RadFormsTest

**Comment by NickIliev** [comment]
@aquinn637 assign height for either the [StackLayout ](https://github.com/aquinn637/RadFormsTest/blob/master/src/app/home/home.component.html#L3)or for your RadDataForm
