### ISSUE TITLE
Nativescript/Angular path issue with Sidedrawer

### ISSUE THREAD

**Issue by caseyjfer** [NativeScript/nativescript-ui-feedback#1338]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Tell us about the problem
Nativescript UI Sidedrawer uses nativescript-angular/element-registry in angular/side-drawer-directives.js which is not functional with @nativescript/angular 8.20.0 due to incorrect pathing

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- nativescript-ui-sidedrawer - 8.0.0
- CLI - 6.3.0
- TNS Core Modules: 6.3.2
- tns-android 6.2.0 tns-ios 6.3.0

### Please tell us how to recreate the issue in as much detail as possible.
tns build <platform>

ERROR in ../node_modules/nativescript-ui-sidedrawer/angular/side-drawer-directives.js
Module not found: Error: Can't resolve 'nativescript-angular/element-registry' in '/Users/<path_to_app>/node_modules/nativescript-ui-sidedrawer/angular'
 @ ../node_modules/nativescript-ui-sidedrawer/angular/side-drawer-directives.js 5:25-73
 @ ./app/app.module.ts
 @ ./main.ts
Executing webpack failed with exit code 2.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

`var element_registry_1 = require("@nativescript/angular/element-registry");` 

instead of

`var element_registry_1 = require("nativescript-angular/element-registry");`

It seems like since nativescript switched to the @ sign pathing for their dependencies, this broke. For some reason, even though the correct nativescript-angular dependency is present, it won't install it, probably because it considers @nativescript/angular to suffice in the app package.

**Comment by NickIliev** [comment]
@caseyjfer you need to have both the scoper and the non-scoped packages to be able to use a scoped path (`@`). For now...
