### ISSUE TITLE
Calendar month view styles for disabled days on iOS not working

### ISSUE THREAD

**Issue by lini** [NativeScript/nativescript-ui-feedback#1367]
Using nativescript@6.4.0 and RadCalendar@6.0.0

When setting a custom `monthViewStyle.dayCellStyle.cellTextColor` for RadCalendar in month view on iOS, the days that should be disabled will be displayed the same as normal days. These include days not between `minDate` and `maxDate`, days from the previous/next month, weekend days. 

The disabled day style is set from the default calendar theme and cannot be changed - no CSS support, no template support, no monthViewStyle support.

Similar to #435, #568, #576

**Comment by NickIliev** [comment]
Reported via t.1456367

**Comment by lini** [comment]
`nativescript-ui-calendar@6.1.0` includes two new properties for the month view styles - `anotherMonthCellStyle` and `disabledCellStyle`, which can have the same styles as `dayCellStyle`. 
Samples showing usage:
- Angular: https://github.com/NativeScript/nativescript-ui-samples-angular/blob/d47e3aa9c97fa9de5b310bc53e2c0361fd5dcca5/calendar/app/calendar/calendar-styles.service.ts#L65
- Vanilla JS/TS: https://github.com/NativeScript/nativescript-ui-samples/blob/master/calendar/app/calendar/cell-styling/cell-styles-page.xml#L39

**Comment by PhilippS93** [comment]
This is still an issue. The style provided by @lini does also not help. The days text of another month days are still in the same color as the day style color.

I use `nativescript-ui-calendar@6.1.0`

**Comment by fklingler** [comment]
This is still not working on nativescript-ui-calendar@7.0.2, and it is a big problem for us.
It's the same for cellBackgroundColor

**Comment by shariebg** [comment]
@fklingler I had the same problem with disabled days. To get it to work, I added `minDate` and `maxDate` to `RadCalendar` in the HTML part. 

Example:
```html
<RadCalendar
    :selectionMode="selectionMode" 
    :monthViewStyle='monthViewStyle' 
    :minDate="minDate" 
    :maxDate="maxDate">
</RadCalendar>
```

`minDate` and `maxDate` I then determined as in this [StackOverflow issue](https://stackoverflow.com/a/13572682/14356107). 

```typescript
get minDate() {
    var date = new Date();
    return new Date(date.getFullYear(), date.getMonth(), 1);
}

get maxDate() {
    var date = new Date();
    return new Date(date.getFullYear(), date.getMonth() + 1, 0);
 }
```

Now my style works for `disabledCellStyle`.
