### ISSUE TITLE
RadDataForm Picker Focus Problem

### ISSUE THREAD

**Issue by DimitrisRK** [NativeScript/nativescript-ui-feedback#1383]
In a RadDataForm, if user has clicked on a TextField, it will get focused (that's normal).
After clicking on that TextField, if one clicks on a Picker field, it won't get focused and page will scroll back to previously focused TextField right after Picker value selection.

Platform: Android

Progress NativeScript UI plugin version: nativescript-ui-dataform ^6.0.0
CLI: 6.4.1
Cross-platform modules: 6.5.0
Runtime: 6.4.1

**Comment by DimitrisRK** [comment]
After having a taste of this component's flaws, I suggest that developers are encouraged to develop their own custom forms.

**Comment by NickIliev** [comment]
Closing due to not enough information provided - please consider posting the required information when reporting a bug (see the bug template below)

```
<!--
PLEASE HELP US PROCESS GITHUB ISSUES FASTER BY PROVIDING THE FOLLOWING INFORMATION.

If the below information is not provided we may not be able to respond and/or assist you in time and your report maybe closed without investigation.
-->

> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

## Please, provide the details below:

### Tell us about the problem
_Please, ensure your title is less than 63 characters long and starts with a capital
letter._

### Which platform(s) does your issue occur on?
_iOS/Android/Both (if applicable tell us the specific version of the platform)_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** (the version of nativescript-ui-* in the `package.json`)
- **CLI:** (run `tns --version` to fetch it)
- **Cross-platform modules:** (the version of tns-core-modules in the `package.json`)
- **Runtime(s):** (the `"tns-android"` and `"tns-ios"` properties in the `package.json`)

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. ...

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_(You can paste entire code snippets, link to playground demo or attach a runnable project)_

```

**Comment by DimitrisRK** [comment]
### Tell us about the problem: Already set.
### Which platform(s) does your issue occur on?: Already set.
### Please provide the following version numbers that your issue occurs with: Already set.
### Please tell us how to recreate the issue in as much detail as possible.: "### Tell us about the problem:" is detailed enough to help recreate the issue.
### Is there code involved?: This sounds very optional.

I would definitely accept more proper answers like "We could not replicate this issue. Please provide more details.", but this answer sounds more like an excuse to neglect this.

That "We have got too many tickets so let's focus on the ones that are easier to reproduce" strategy is solid proof that the staff needs more people in support section.

I love this framework, and I'm getting quite disappointed at how poorly bug reports are handled. At this rate, bugs like this might still be there for few more years.
