### ISSUE TITLE
Expose method similar to getFirstVisiblePosition() for Android (like isItemAtIndexVisible in ListView)

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-ui-feedback#28]
Feature request made by @NathanaelA  (with admin ticket 1073577)
Create a public method which can return your current visible position in the list-view (without having to trigger itemTap and args.itemIndex)

Similar to [https://developer.android.com/reference/android/widget/AdapterView.html#getFirstVisiblePosition()](https://developer.android.com/reference/android/widget/AdapterView.html#getFirstVisiblePosition())

> The normal getFirstVisiblePosition on a list view does not work on the RLV, how exactly can I get the currently displayed position so I can reset it back?

> Any other ideas on how to get the Actual index of the current item showing?    Can we drop an enhancement request for this?
> The issue is really what you are talking about; saving the current location navigating to another page, and then returning I want to position the listview as close to before as possible...    However, I have no access to the itemSelected event as they might hit one of any number of buttons in the listview item, and so those directly catch the event and don't pass it on to the listview for it to fire the selection event on Android. 

Similar or identical to [`isItemAtIndexVisible` in the core ListView](https://docs.nativescript.org/api-reference/classes/_ui_list_view_.listview#isitematindexvisible)

**Comment by NathanaelA** [comment]
Just a follow up; I'm still needing this function/value; I also need it because on orientation change will cause on iOS the display to reset to the first cell if you change the layout style.

**Comment by anuragd7** [comment]
+ 1

**Comment by tigrenok00** [comment]
+1

**Comment by ingelity** [comment]
+1

**Comment by digitalhurricane-io** [comment]
+1

**Comment by NickIliev** [comment]
+1 from t.1363684

**Comment by danieltran** [comment]
+1

**Comment by zbranzov** [comment]
Released in nativescript-ui-listview@6.4.0
