### ISSUE TITLE
[Feature request] Ability to change the token backgroundColor for the AutoCompleteTextView

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-ui-feedback#328]
Providing functionality, which allows setting the backgroundColor for the selected tokens in the `AutoCompleteTextView` component as it is shown in the image below:
<img width="170" alt="autocomplete-overview-ios" src="https://user-images.githubusercontent.com/17448734/31335534-a63a536c-acfb-11e7-9e4c-f5ebdef885fb.png">

**Comment by anuragd7** [comment]
+1

**Comment by joshcomley** [comment]
Hi there - has this had any progress in NativeScript 6?

**Comment by tgpetrov** [comment]
Hi guys,
We have recently added CSS Support for RadAutoCompleteTextView in nativescript-ui-autocomplete@5.1.0 which also includes the Tokens in its normal and selected states.
Here are the docs and examples:
* NS Core - [docs](https://docs.nativescript.org/ui/components/AutoCompleteTextView/autocomplete-getting-started#apply-css), [example](https://github.com/NativeScript/nativescript-ui-samples/tree/master/autocomplete/app/examples/css)
* NS with Angular - [docs](https://docs.nativescript.org/angular/ui/ng-components/ng-AutoCompleteTextView/getting-started#apply-css), [example](https://github.com/NativeScript/nativescript-ui-samples-angular/tree/master/autocomplete/app/examples/css)
* NS with Vue - [docs](https://docs.nativescript.org/vuejs/ns-ui/AutoCompleteTextView/getting-started#apply-css), [example](https://github.com/NativeScript/nativescript-ui-samples-vue/tree/master/autocomplete/app/examples/CssStyle)
