### ISSUE TITLE
Setting Transparent color not possible for iOS RadDataForm editors

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-ui-feedback#409]
Case:  A scenario where we would want to set transparent colors to our data form editors.
Result: the editors (or the layer above) are always set to white color on iOS.

For example:
```
<GridLayout backgroundColor="green">
    <df:RadDataForm source="{{ employee }}" editorUpdate="dfEditorUpdate" backgroundColor="transparent">
</GridLayout>
```

and the `dfEditorUpdate` method
```
export function dfEditorUpdate(args: DataFormEventData) {
    var entityProperty = <EntityProperty>(<RadDataForm>args.object).getPropertyByName(args.propertyName);
    entityProperty.editor.propertyEditorStyle.fillColor = "#00555555"; // here we can only pass string e.g. "LightBlue" or hex value - however the Color module also can accepts ARGB number values which is not possible for the property
}
```

The fillColor property is accepting only a string as a value which makes providing ARGB number values not possible (as the fillColor source code is actually using the Color module it would be more applicable to have the option to provide an object value). Even when the source code is hardcoded to pass `new Color(0. 100. 55. 255)` the area behind the editors is white and not transparent.

**Comment by NickIliev** [comment]
+1 reported via t. 1140412

**Comment by NickIliev** [comment]
as a workaround instead of `transparent`, we can set hex color with alpha opacity for `fillColor` property.
```
<TKPropertyEditorStyle tkPropertyEditorStyle fillColor="#0000FFFF" ></TKPropertyEditorStyle
```
 Kudos to M.Geller for the provided solution.

**Comment by tgpetrov** [comment]
The editors of RadDataForm can now be made transparent. Here is an example in [NS Core](https://github.com/NativeScript/nativescript-ui-samples/tree/master/dataform/app/examples/styling/css-form) and [NS + Angular](https://github.com/NativeScript/nativescript-ui-samples-angular/tree/master/dataform/app/examples/styling/css-form).
