### ISSUE TITLE
Autocomplete - styling the SuggestionView

### ISSUE THREAD

**Issue by jnorkus** [NativeScript/nativescript-ui-feedback#612]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
I can't find any way to put the SuggestionView **under** the autocomplete text field. I would also like a custom background color, etc.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.6.0
- **CLI:** 3.4.3
- **Cross-platform modules:** 3.4.0
- **Runtime(s):** 3.4.2

### Please tell us how to recreate the issue in as much detail as possible.
1. Use the Autocomplete sample
2. Add CSS or layout to push the autocomplete text field a bit towards bottom
Result: when typing, suggestions appear on top of the text field

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
All necessary code is in documentation

**Comment by tsonevn** [comment]
HI @jnorkus 
First of all, thank you for your interest in UI for NativeScript.

Regarding the Autocomplete component suggestion position. In the current state, all suggestion will be displayed below the Autocomplete field.
Regarding the styling, you could set up the style in the Layout container inside the suggestionItemTemplate. For example:
```
<au:RadAutoCompleteTextView id="autocmp" items="{{ dataItems }}" suggestMode="Suggest" displayMode="Tokens">
            <au:RadAutoCompleteTextView.suggestionView>
                <au:SuggestionView>
                    <au:SuggestionView.suggestionItemTemplate>
                        <StackLayout backgroundColor="green" orientation="vertical" padding="10">
                            <Label text="{{ text }}"></Label>
                        </StackLayout>
                    </au:SuggestionView.suggestionItemTemplate>
                </au:SuggestionView>
            </au:RadAutoCompleteTextView.suggestionView>
         </au:RadAutoCompleteTextView>
```
In the sample, I set up the StackLayout `backgroundColor` to green.
 

Let me know, if I am missing something.

**Comment by jnorkus** [comment]
For me the SuggestionView was displayed above the autocomplete field. I needed it below. You can style the StackLayout but I was unable to style the SuggestionView container.

Anyway, I went on to create my own custom Autocomplete using a TextField and a ListView - works like a charm.

**Comment by tsonevn** [comment]
Hi @jnorkus,
Indeed the SuggestionView could not be styled at this time. Regarding that, I am marking this as a feature request.

Regarding the Suggestions position, it would help if you provide sample project, which demonstrates the case and could be used for debugging.

**Comment by waszqba** [comment]
Hi, I would like to add another suggestion in regard to styling SuggestionView.
It would be great to have an ability to set either z-index or any other property so it wouldn't get cropped to the size of a modal if it's used in one. I've just experienced this issue and tried to set the suggestionView to kind of 'fall out' of the modal, as the modal itself is really short.

**Comment by keithgulbro** [comment]
@tsonevn Thanks for responding to this issue. Has there perhaps been any updates to the availability to styling the SuggestionView. More specifically, I'm attempting to add a background color to the SuggestionView container, it currently renders as plain white, with no options to change. Any insight you may have would be helpful. Thanks in advance!

**Comment by tsonevn** [comment]
Hi @keithgulbro,
This feature is still under review. Currently, I can not commit to the exact time, when this functionality will be available.

**Comment by tgpetrov** [comment]
We have recently added CSS Support for RadAutoCompleteTextView in nativescript-ui-autocomplete@5.1.0 which also includes the SuggestionView.
Here are the docs and examples:
* NS Core - [docs](https://docs.nativescript.org/ui/components/AutoCompleteTextView/autocomplete-getting-started#apply-css), [example](https://github.com/NativeScript/nativescript-ui-samples/tree/master/autocomplete/app/examples/css)
* NS with Angular - [docs](https://docs.nativescript.org/angular/ui/ng-components/ng-AutoCompleteTextView/getting-started#apply-css), [example](https://github.com/NativeScript/nativescript-ui-samples-angular/tree/master/autocomplete/app/examples/css)
* NS with Vue - [docs](https://docs.nativescript.org/vuejs/ns-ui/AutoCompleteTextView/getting-started#apply-css), [example](https://github.com/NativeScript/nativescript-ui-samples-vue/tree/master/autocomplete/app/examples/CssStyle)
