### ISSUE TITLE
AutoComplete not giving tokens

### ISSUE THREAD

**Issue by waszqba** [NativeScript/nativescript-ui-feedback#657]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

## Please, provide the details below:
I try to create a modal with autocomplete that is given a list of things to suggest from, and I want the modal to pass all the added tokens to its mother component, so I can work with them further on.
When I close the modal, I can `console.log` the output of `this.autocmp.autoCompleteTextView.tokens()`, but an empty object with some kind of constructor is passed to any variable or function I want to assign it to. Also, trying to call the method in debugger without wrapping it in `console.log()` gives me a blank object, but just after executing it this way, wrapping it in `console.log()` shows me the contents of autocomplete.
BTW, I tried to reproduce the issue with the attached playground project, but it crashes as soon as I type any character into the AutoCompleteTextView.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Which platform(s) does your issue occur on?
_Android_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** autocomplete: ^3.6.0
- **CLI:** 4.0.0
- **Cross-platform modules:** ~3.4.0
- **Runtime(s):** android: 4.0.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. Open the modal
3. Start typing some country name
// if it won't crash, continue
4. Add a token or two
5. Tap outside the modal so it closes
6. Check the console.log

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_(You can paste entire code snippets or attach a runnable project)_
[playground](https://play.nativescript.org/?template=play-ng&id=aHraMG&v=10)

**Comment by tsonevn** [comment]
Hi @waszqba,
The issue in the playground project was related to the data, which was set up to the suggestion array. If you replace the following code in the modal page constructor, the project will be built properly:
```
constructor(private params: ModalDialogParams,
        page: Page) {
        page.on('unloaded', () => this.close());
        this.filters = new ObservableArray<TokenModel>();
        for (const item of params.context.filters) {
            this.filters.push(new TokenModel(item, null));
            
        }
    }
```
Regarding the `tokes()` method. At this time the method will return an array of the native views. To get only the name of the selected tokens, you can use the following piece of code:
```
 close() {
        var array = [];
        if (isAndroid) {
            array.push((this.autocmp.nativeElement.tokens().get(0).getModel().getText()));
        } else {
            array.push(this.autocmp.autoCompleteTextView.tokenAtIndex(0).text);
        }
        this.params.closeCallback(array);
    }
```
Also, I will mark this issue as a feature, and we will research how to simplify the process of getting tokens

**Comment by waszqba** [comment]
Thank you, @tsonevn!
I'm looking forward to see this project grow :)

**Comment by suparnavg** [comment]
@tsonevn facing the same issue with an autocomplete EntityProperty in a raddataform. Would be super helpful to clear this up maybe in the UI examples project - even if just a comment - spent a ton of time trying to figure out what was going on! 😄

**Comment by tsonevn** [comment]
HI @suparnavg,
This is a missing feature, we will update the issue and docs when this functionality is available.

**Comment by suparnavg** [comment]
Thank you! Look forward to the update.. in the meanwhile I'll look for an alternative to this raddataform

**Comment by tgpetrov** [comment]
Hi guys,
`RadAutoCompleteTextView` now has a `selectedTokens` property which you can use to check which tokens are currently selected. Here's [an example](https://play.nativescript.org/?template=play-ng&id=HfzniG) in the Playground.
The `AutoCompleteInline` editor in `RadDataForm` provides the currently selected tokens as value of the related `EntityProperty`. This is demonstrated in the demo apps for [NativeScript Core](https://github.com/NativeScript/nativescript-ui-samples/tree/master/dataform/app/examples/editors/autocomplete) and [NativeScript with Angular](https://github.com/NativeScript/nativescript-ui-samples-angular/tree/master/dataform/app/examples/editors/autocomplete).
