### ISSUE TITLE
[RadAutoCompleteTextView] - Can't style SuggestionView for iOS

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-ui-feedback#67]
Related to t.1092095 (native solution provided in the ticket)

While in Android the background color for the whole **SuggestionView** can be set globally by setting the color of the whole **RadAutoCompleteTextView** for iOS this is not possible neither with styling the whole RadAutoCompleteTextView,, nor with styling the SuggestionView. Styling the inner template layouts will style only each suggestion template but a lot of white space will remain (depending on **suggestionViewHeight** size).

Expected result when setting background-color for SuggestionView
![d29ed653-07d6-4e61-93eb-a21fe8ee6e0a_elimina2](https://cloud.githubusercontent.com/assets/18008302/23257716/b37b06c0-f9cd-11e6-9d77-dc27db661816.png)

Actual Result:
![795e14c2-87df-46e4-9df3-6f16729c9987_elimina](https://cloud.githubusercontent.com/assets/18008302/23257723/babcad12-f9cd-11e6-93f0-71ae2bfdcd72.png)

**Comment by anuragd7** [comment]
+1

**Comment by vultix** [comment]
Has anyone found a work-around for this issue?

**Comment by keithgulbro** [comment]
@NickIliev Any update on this? Still looking for a solution. Any assistance would be greatly appreciated!

**Comment by tgpetrov** [comment]
Hi guys,
We have added CSS Support for RadAutoCompleteTextView in nativescript-ui-autocomplete@5.1.0
Here are the docs and examples:
* NS Core - [docs](https://docs.nativescript.org/ui/components/AutoCompleteTextView/autocomplete-getting-started#apply-css), [example](https://github.com/NativeScript/nativescript-ui-samples/tree/master/autocomplete/app/examples/css)
* NS with Angular - [docs](https://docs.nativescript.org/angular/ui/ng-components/ng-AutoCompleteTextView/getting-started#apply-css), [example](https://github.com/NativeScript/nativescript-ui-samples-angular/tree/master/autocomplete/app/examples/css)
* NS with Vue - [docs](https://docs.nativescript.org/vuejs/ns-ui/AutoCompleteTextView/getting-started#apply-css), [example](https://github.com/NativeScript/nativescript-ui-samples-vue/tree/master/autocomplete/app/examples/CssStyle)
