### ISSUE TITLE
candlestick color problem

### ISSUE THREAD

**Issue by cheungcl** [NativeScript/nativescript-ui-feedback#767]
In the example: https://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Chart/Series/Financial/candlestick   

vs the definition of candlestick:
https://stockcharts.com/articles/mailbag/2014/05/whats-the-difference-between-solid-and-filled-candlesticks.html

The hollow and filled color of your implementation seems the reverse of a normal interpretation.

Also, is it possible to change the filled color and edge color of the candlesticks ?

Thanks a lot.

**Comment by tsonevn** [comment]
Hi @cheungcl,
You can style the  `Series` while using the Palette. You can find more info [here](https://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/Chart/Series/styling). Regarding your case, you can set up `strokeColor`, ` fillColor` property, which will change the filled and edge colours. For example:
```
<RadCartesianChart tkExampleTitle tkToggleNavButton>
  <DateTimeCategoricalAxis tkCartesianHorizontalAxis dateFormat="yyyy-MM-dd" verticalLocation="Bottom"></DateTimeCategoricalAxis>
  <LinearAxis tkCartesianVerticalAxis></LinearAxis>

  <CandlestickSeries seriesName="test" tkCartesianSeries cornerRadius="30"  categoryProperty="Date" openPropertyName="Open" highPropertyName="High" lowPropertyName="Low"
    closePropertyName="Close" [items]="candleStickSourceItems"></CandlestickSeries>
    <Palette tkCartesianPalette seriesName="test">
      <PaletteEntry tkCartesianPaletteEntry cornerRadius="30"  fillColor="green"  strokeColor="red"></PaletteEntry>
  </Palette>
  </RadCartesianChart>
```
Bear in mind that the `fillColor` will be applied only on iOS. It seems that there is a bug with this property for Android.

**Comment by tgpetrov** [comment]
@cheungcl while I agree with you that in general the hollow is more appropriate for candles where the close price is higher than the open price, I believe the color choice is also important - if the fill is red it hints a decline in price, while another if another fill (like black) is used this would not be so clear. As of 7.0.0 the color of the candles and their fill can be easily changed through CSS or through the series API as shown [here](https://docs.nativescript.org/ui/components/Chart/Series/styling#chart-series-styling).

In short, you simply provide a list of two colors for the fills and two colors for the strokes - the first colors from these lists are used to draw the bullish points (whose close value is higher than their open value) and the second colors - to draw the bearish points (whose close value is lower than their open value). You can provide transparent - for each of the options so you can fulfil your design requirement. There is also an example in out Sample apps for [NativeScript Core](https://github.com/NativeScript/nativescript-ui-samples/blob/master/chart/app/examples/css/candlestick-css-page.css#L70), [NativeScript with Angular](https://github.com/NativeScript/nativescript-ui-samples-angular/blob/master/chart/app/examples/css/chart-css-candlestick.component.css#L52) and [NativeScript with Vue](https://github.com/NativeScript/nativescript-ui-samples-vue/blob/master/chart/app/examples/css/CandlestickCss.ts#L106).

**Comment by topclaudy** [comment]
@tgpetrov Styling with CSS doesn't seem to work
