### ISSUE TITLE
RadListView. Does RadListView support tap event for view (not for items)?

### ISSUE THREAD

**Issue by Chehow** [NativeScript/nativescript-ui-feedback#891]
Hi There

Looks like (tap)='onListViewTap($event)' does not work for RadListView while it works fine for ListView. Is there any possibility to handle 'tap' event on whole list view area.

Thank you

**Comment by tsonevn** [comment]
HI @Chehow,
Can you provide some sample code, which demonstrates how you are setting up the `tap` event to the RadListView and if there are some other events set to the component? Also, Is this issue platform specific(iOS/Android)?

**Comment by Chehow** [comment]
Hi @tsonevn 

Please check this playground: https://play.nativescript.org/?template=play-ng&id=i6ntdo&v=9
It does not work here but if you change it from <RadListView> to <ListView> then '(tap)' event works fine. '(itemTap)' works fine for RadListView but I need to handle tap event on whole list view area (not a specific item)

I check it on Android device.
Thank you in advice.

**Comment by tsonevn** [comment]
Hi @Chehow 
The `tap` seems to work as expected on iOS. The event will not be executed only on Android.

**Comment by academici** [comment]
@tsonevn , i using radlistview + vue, tap event dont work in v-template items

```js
<RadListView
        class="cart-list"
        ref="listView"
        for="(item, i) in cartItems"
      >
        <v-template>
          <Label class="cart-item" text="item" @tap="alert('tap')" />
        </v-template>
</RadListView>
```

**Comment by tgpetrov** [comment]
Hi @Chehow and @academici 
The issue with the tap event in the view part of the v-template has been resolved.
Here's [a Playground](https://play.nativescript.org/?template=play-vue&id=NYXa8i) that demonstrates this. Just tap on an item and observe the console logs.
