### ISSUE TITLE
Setting margin in Pie Chart series has no effect in Android

### ISSUE THREAD

**Issue by etabakov** [NativeScript/nativescript-ui-feedback#955]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Which platform(s) does your issue occur on?
_Android_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.9.1
- **CLI:** 5.0.0
- **Cross-platform modules:** 5.0.2
- **Runtime(s):** 5.0.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Create an app with pie chart.
2. Set the margin property to the Label of the Series
3. Run the app on Android and iOS

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```
                <RadPieChart height="100%" allowAnimation="true" row="1" col="0">
                    <PieSeries tkPieSeries selectionMode="DataPoint" expandRadius="0.2" outerRadiusFactor="0.7" [items]="items$ | async"
                        valueProperty="RunsCount" legendLabel="City" showLabels="true">
                        <PointLabelStyle tkPieLabelStyle fontStyle="Bold" fillColor="#00aeef" textSize="13" textColor="White" margin="20"></PointLabelStyle>
                    </PieSeries>
                    <RadLegendView tkPieLegend position="Right" title="Routes" offsetOrigin="TopRight" enableSelection="true" width="150"></RadLegendView>
                </RadPieChart>
```

For iOS the labels are being moved away from the center of the pie chart as you increase the margin value. For Android - they stay pretty close to the center and doesn't move at all (see the image attached).
<img width="786" alt="screen shot 2018-12-01 at 15 13 17" src="https://user-images.githubusercontent.com/2611328/49328563-b4eccb00-f57b-11e8-9072-607e0d0c013e.png">

**Comment by tgpetrov** [comment]
As of nativescript-ui-chart@7.0.0 the above issue is no longer observed.
