### ISSUE TITLE
The possibility of writing inside a PieChart DonutSeries (Subtitle)

### ISSUE THREAD

**Issue by mostafaSYR** [NativeScript/nativescript-ui-feedback#987]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Tell us about the problem
_I don't seem to find a way to write something inside a PieChart DonutSeries, in the empty place off course._

### Which platform(s) does your issue occur on?
_Both_

**Comment by mostafaSYR** [comment]
anyone ??!! :)

**Comment by tgpetrov** [comment]
Hi @mostafaSYR 
We decided against the option to allow this as part of the Chart UI as this would have limited styling capabilities. On the other hand, currently it is quite simple to add a label, image or any custom UI that you would like inside the Donut, by simply placing this UI on top of the chart.

Here are examples in our demo apps: [NativeScript Core](https://github.com/NativeScript/nativescript-ui-samples/blob/master/chart/app/examples/css/donut-css-page.xml#L26), [NativeScript with Angular](https://github.com/NativeScript/nativescript-ui-samples-angular/blob/master/chart/app/examples/css/chart-css-donut.component.html#L25), https://github.com/NativeScript/nativescript-ui-samples-vue/blob/master/chart/app/examples/css/DonutCss.ts#L38:
![chart-css-donut-01-ios](https://user-images.githubusercontent.com/6085251/68583108-0a687200-0485-11ea-913a-381801d355dd.png)
