### ISSUE TITLE
Labels on Bar Chart are overlapping when the series is configured in horizontal orientation on Android

### ISSUE THREAD

**Issue by etabakov** [NativeScript/nativescript-ui-feedback#998]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Tell us about the problem
Labels on Bar series are overlapping when the series is configured in horizontal orientation.

### Which platform(s) does your issue occur on?
_Android_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** nativescript-ui-chart - 3.11.1 
- **CLI:** 5.1
- **Cross-platform modules:** 5.1
- **Runtime(s):** 5.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Create a Bar Chart with CategoricalAxis as vertical axis and LinearAxis as horizontal axis.
2. Give some data.
3. Show the labels of the bar series.
4. Open on Android and notice that on top labels are overlapping and the chart is unusable (see the screenshot)
![image](https://user-images.githubusercontent.com/2611328/51548039-26f0da80-1e70-11e9-8062-2f8ed4fd900e.png)

Reproduction of the problem can be checked out in [this Playground](https://play.nativescript.org/?template=play-ng&id=aqVBkB&v=3)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Check the Playground.

Looks like related to this issue: https://github.com/telerik/nativescript-ui-feedback/issues/249

**Comment by tgpetrov** [comment]
As of nativescript-ui-chart@7.0.0 the above issue is no longer observed, which is visible from the following sample in the sample apps for [NativeScript Core](https://github.com/NativeScript/nativescript-ui-samples/blob/master/chart/app/examples/css/bar-css-page.xml), [NativeScript with Angular](https://github.com/NativeScript/nativescript-ui-samples-angular/blob/master/chart/app/examples/css/chart-css-bar.component.html) and [NativeScript with Vue](https://github.com/NativeScript/nativescript-ui-samples-vue/blob/master/chart/app/examples/css/BarCss.ts):
![chart-css-bar-01-android](https://user-images.githubusercontent.com/6085251/68483936-1239d380-0245-11ea-8046-6286caf361df.png)
